all:
	convert collaborate.png -trim collaborate.png
	convert communicate.png -trim communicate.png
	convert familiar.png -trim familiar.png
	convert dontknow.png -trim dontknow.png 
	convert true_graph.png -trim true_graph.png
	convert inferred_graph.png -trim inferred_graph.png
